---
title: Что такое исключение?
draft: false
tags:
  - "#JavaScript"
  - "#try-catch"
info:
---
Чтобы `try..catch` работал, код должен быть выполнимым. Другими словами, это должен быть корректный JavaScript-код.

Он не сработает, если код синтаксически неверен, например, содержит несовпадающее количество фигурных скобок:

```javascript
try {   {{{{{{{{{{{{ } catch(e) {
	alert("Движок не может понять этот код, он некорректен");
}
```

JavaScript-движок сначала читает код, а затем исполняет его. Ошибки, которые возникают во время фазы чтения, называются ошибками парсинга. Их нельзя обработать (изнутри этого кода), потому что движок не понимает код.

Таким образом, `try..catch` может обрабатывать только ошибки, которые возникают в корректном коде. Такие ошибки называют «ошибками во время выполнения», а иногда «исключениями».

Исключение, которое произойдёт в коде, запланированном «на будущее», например в `setTimeout`, `try..catch` не поймает:

```javascript
try {
	setTimeout(function() {
	noSuchVariable; // скрипт упадёт тут   }, 1000);
} catch (e) {
	alert( "не сработает" );
}
```

Это потому, что функция выполняется позже, когда движок уже покинул конструкцию `try..catch`.

Чтобы поймать исключение внутри запланированной функции, `try..catch` должен находиться внутри самой этой функции:

```javascript
setTimeout(function() {
	try {
		noSuchVariable; // try..catch обрабатывает ошибку!
	} catch {
		alert( "ошибка поймана!" );
	}
}, 1000);`
```

---

[[003 JSCore|Назад]]